Updated Dockerfiles and deployments

diff --git a/app/Dockerfile b/app/Dockerfile
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -1,9 +1,32 @@
-FROM python:3.11-slim-bookworm
+FROM --platform=linux/amd64 python:3.12-slim AS build_amd64
+
+ENV PIP_DEFAULT_TIMEOUT=100 \
+    # Allow statements and log messages to immediately appear
+    PYTHONUNBUFFERED=1 \
+    # disable a pip version check to reduce run-time & log-spam
+    PIP_DISABLE_PIP_VERSION_CHECK=1 \
+    # cache is useless in docker image, so disable to reduce image size
+    PIP_NO_CACHE_DIR=1
+
 RUN mkdir /my_flask_app
 WORKDIR /my_flask_app
 COPY requirements.txt /my_flask_app
-RUN pip install --upgrade pip
-RUN pip install --no-cache-dir -r requirements.txt
+
+RUN set -ex \
+    # Create a non-root user
+    && addgroup --system --gid 1001 appgroup \
+    && adduser --system --uid 1001 --gid 1001 --no-create-home appuser \
+    # Upgrade the package index and install security upgrades
+    && apt-get update -y \
+    && apt-get upgrade -y \
+    # Install dependencies
+    && pip install --upgrade pip \
+    && pip install -r requirements.txt \
+    # Clean up
+    && apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*  
+    
 COPY app/. /my_flask_app
 EXPOSE 8080
 ENTRYPOINT [ "gunicorn", "-b :8080", "app:app", "--log-file=-","--reload","--access-logfile=-", "--workers=2" ,"--threads=4", "--worker-class=gthread" ]
